'use server'

import { revalidatePath } from 'next/cache'
import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import type { Edition } from '@/lib/types/dnd'

export interface ActionState {
  error?: string
}

/**
 * Create a campaign. The caller becomes the DM; a trigger inserts their
 * `campaign_members` row, and the invite code is generated by the DB default.
 */
export async function createCampaignAction(
  _prev: ActionState,
  formData: FormData,
): Promise<ActionState> {
  const name = String(formData.get('name') ?? '').trim()
  const editionRaw = String(formData.get('edition') ?? '2024')
  const edition: Edition = editionRaw === '2014' ? '2014' : '2024'

  if (!name) return { error: 'Give your campaign a name.' }
  if (name.length > 120) return { error: 'That name is a bit long (120 chars max).' }

  const supabase = await createClient()
  const {
    data: { user },
  } = await supabase.auth.getUser()
  if (!user) redirect('/login')

  const { error } = await supabase
    .from('campaigns')
    .insert({ name, edition, dm_user_id: user.id })

  if (error) return { error: error.message }

  revalidatePath('/app')
  redirect('/app')
}

/** Join an existing campaign as a player via its invite code. */
export async function joinCampaignAction(
  _prev: ActionState,
  formData: FormData,
): Promise<ActionState> {
  const code = String(formData.get('code') ?? '').trim()
  if (!code) return { error: 'Enter an invite code.' }

  const supabase = await createClient()
  const {
    data: { user },
  } = await supabase.auth.getUser()
  if (!user) redirect('/login')

  const { error } = await supabase.rpc('join_campaign', { code })

  if (error) {
    return {
      error: /invalid invite code/i.test(error.message)
        ? "That invite code didn't match a campaign."
        : error.message,
    }
  }

  revalidatePath('/app')
  redirect('/app')
}
